{"name": "test_login_usernameFormat_error", "status": "passed", "attachments": [{"name": "log", "source": "4bef8845-b46b-4b16-8b8c-073f5bb6a69a-attachment.txt", "type": "text/plain"}], "start": 1610613131684, "stop": 1610613135510, "uuid": "baf4c780-2648-4ba2-ad8c-b81644813d22", "historyId": "b7c9963723357b0faf6d03130d678f90", "testCaseId": "e5bc1aeb101de12749be698a7235f84d", "fullName": "TestCases.test_logincase.test_login.Test_Login#test_login_usernameFormat_error", "labels": [{"name": "story", "value": "测试账号错误"}, {"name": "parentSuite", "value": "TestCases.test_logincase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "USER-20190821YP"}, {"name": "thread", "value": "3696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_logincase.test_login"}]}